# Dados do site
site_name: Guia Steam Translation Brasil
site_description: Guia de tradução da equipe brasileira do Steam Translation
site_author: Equipe STS Brasil
site_url: http://sts.berna.zone
repo_url: https://github.com/Berna-L/documentacao-sts-brasil
copyright: Valve, Steam e Steam Translation são marcas e/ou marcas registradas da Valve Corporation.<br/>
  Demais marcas e marcas registradas citadas e/ou ilustradas nesta documentação são propriedade
  dos seus respectivos donos.
#Nome do repositório (no canto sup dir)
repo_name: 'Contribua!'

#Listagem de páginas
pages:
  - Início: 'index.md'
  - Candidatos:
      - 'Informações gerais': 'candidatos/index.md'
      - Dicas: 'candidatos/dicas.md'
      - Regras: 'candidatos/regras.md'
  - Tradutores externos: 'externos/index.md'
  - Jogos:
      - Artifact: 'jogos/artifact.md'
      - Dota 2:
        - 'Informações gerais': 'jogos/dota2/index.md'
        - 'Glossário': 'jogos/dota2/glossario.md'
  - Apêndice:
      - Produtos disponíveis: 'apendice/produtos-disponiveis.md'

# Configurações do tema
theme:
  name: 'material'
  language: 'pt'
  font:
    text: 'PT Sans'
  palette:
    primary: 'blue grey'
  logo:
    # Pra ficar que nem as três bandeirinhas do STS
    icon: 'flagflagflag'

#Configurações extras
extra:
  search:
    language: 'pt'
  # Ícones no rodapé
  social:
  - type: 'globe'
    link: https://translation.steampowered.com
  - type: 'steam'
    link: 'https://steamcommunity.com/groups/STSBrasil'

# Extensões
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs